### PR TITLE
EZP-27292: Initialize the documentation

### PR DESCRIPTION
**Pull request by jacek-foremski**
This PR adds missing documentation files to the documentation branch, so it will be in sync with the current master branch.
The documentation was added to the master branch in following PR: #12.

### CODE REVIEW

**Review by bdunogier — APPROVED** [review]
Looks okay to me. @mere-teresa, 2nd review ?

**Comment by jacek-foremski** [comment]
I added changes from #17.
@mere-teresa please review.

**Comment by mere-teresa** [comment]
Seems ok to me, as well.

- index.md is full of content
- links seem corrects

**Comment by jacek-foremski** [comment]
I squashed the commits. Ready to be merged.

**Comment by bdunogier** [comment]
@mere-teresa can you review and merge if you agree ?

**Review by mere-teresa — APPROVED** [review]

**Pull request merged**
