### PR TITLE
EZP-27293: Add content and edit views

### PR DESCRIPTION
**Pull request by jacek-foremski**
Rebased changes from #7. 
JIRA: [EZP-27293](https://jira.ez.no/browse/EZP-27293)

> This PR aims at adding the content and edit views for creating/editing/viewing EzTweet Content Items.
As I am not a YUI expert it was mostly developed by copying and editing views from core field types.

**Commit `Add content and edit view` should be reordered after merging to take a place after `Add field view and field definition view templates` and before `Add a validation`.**

Related documentation changes: #31 .

### CODE REVIEW

**Comment by webhdx** [comment]
👍

**Comment by bdunogier** [comment]
> `fixup! Helper for tagging tutorial steps`

:(

**Comment by jacek-foremski** [comment]
@bdunogier It's on purpose. These commits are squashed afterwards, as the master branch is rebased. Master branch is always rebased in this repository since we are keeping the commit history clean. We were discussing this procedure together, do you remember?

**Comment by bdunogier** [comment]
Oh, yeah, because it amends a commit that isn't in this PR. My bad.

Yeah, it is the only way then. Good :)

**Pull request merged**
